sillsdev/flexbridge

DistFiles/about.htm, DistFiles/localizations/Chorus.en.tmx, DistFiles/localizations/Chorus.es.tmx, DistFiles/localizations/Chorus.fr.tmx, DistFiles/localizations/Chorus.zh-Hans.tmx, DistFiles/localizations/FlexBridge.es.tmx, DistFiles/localizations/FlexBridge.fr.tmx, DistFiles/localizations/Palaso.en.tmx, DistFiles/localizations/Palaso.es.tmx, DistFiles/localizations/Palaso.fr.tmx, DistFiles/localizations/Palaso.zh-Hans.tmx, Makefile, ReadMe.md, UpdateDependencies.sh, build/build.common.proj, debian/changelog, debian/control, debian/docs, src/CommonAssemblyInfo.cs, src/Installer/Beta.htm, src/Installer/Installer.wixproj, src/Installer/ReleaseNotes.md
There were some commits on Beta that had not yet made there way into master. This will resolve that.
=> Merge beta branch into master

Makefile, build/build.common.proj, src/Installer/Alpha.htm, src/Installer/ReleaseNotes.md, src/Installer/index.htm
* Change version numbers in build files and documentation
* Change documenatation to indicate Alpha release
=> Make changes to set version of master to 2.3.0

Makefile, debian/control, download_dependencies_linux.sh, lib/common/run-app
* update debian dependencies with mono-sil and geckofx29
* update run-app script to use new mono and gecko
* modify the make file to use the download dependencies script
* install MercurialExtensions
=> Update debian dependencies to build with mono-sil and use curl

debian/control
* Since pkg-config is needed, and wget has trouble with a certificate.
=> Add pkg-config and curl Build-Depends

debian/control
* Needed by at least one machine's pbuilder.
=> Add ca-certificates build-depend

Makefile, lib/common/fieldworks-chorushub, lib/common/run-app-service
The launcher needs to use "mono-service" to launch the
program as a daemon on linux. (LT-16587)
=> Make chorushub run as a service

Makefile
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/58)
=> Update the Makefile so it works on the packaging machine

.gitignore, Makefile, build/FLExBridge.build.mono.proj, make-source-package.sh, src/TriboroughBridge-ChorusPlugin/Properties/CommonResources.resx
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/59)
=> Correct some linux build and packaging problems

build/FLExBridge.build.mono.proj
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/60)
=> Move the stamped about into the output folder during the build

make-source-package.sh
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/66)
=> Include original source package when building package

download_dependencies_linux.sh, download_dependencies_windows.sh
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/68)
=> Download Deps from latest non-WS-changes Chorus and Libpalaso

src/FLEx-ChorusPlugin/FLEx-ChorusPlugin.csproj, src/FLEx-ChorusPlugin/Infrastructure/ActionHandlers/SendReceiveActionHandler.cs, src/FLEx-ChorusPlugin/Infrastructure/FlexBridgeSynchronizerAdjunct.cs, src/FLEx-ChorusPlugin/Infrastructure/FlexFolderSystem.cs, src/FLEx-ChorusPlugin/Infrastructure/Handling/ConfigLayout/DictionaryConfigurationHandlerStrategy.cs, src/FLEx-ChorusPlugin/Infrastructure/Handling/FwLinkArgs.cs, src/FLEx-ChorusPlugin/Infrastructure/SharedConstants.cs, src/TriboroughBridge-ChorusPlugin/CommandLineProcessor.cs, src/TriboroughBridge-ChorusPlugin/Utilities.cs
TODO: special merge step for *.fwdictconfig
[Review on Reviewable](https://reviewable.io/reviews/sillsdev/flexbridge/67)
=> LT-16773: Include new Dictionary Configs in Send/Receive

src/FLEx-ChorusPlugin/Infrastructure/ActionHandlers/SendReceiveActionHandler.cs, src/FLEx-ChorusPlugin/Infrastructure/Handling/ConfigLayout/DictionaryConfigurationHandlerStrategy.cs, src/FLEx-ChorusPlugin/Infrastructure/SharedConstants.cs, src/FLEx-ChorusPluginTests/FLEx-ChorusPluginTests.csproj, src/FLEx-ChorusPluginTests/FieldWorksTestServices.cs, src/FLEx-ChorusPluginTests/Infrastructure/Handling/Anthropology/FieldWorksAnthropologyTypeHandlerTests.cs, src/FLEx-ChorusPluginTests/Infrastructure/Handling/ConfigLayout/DictionaryConfigurationHandlerStrategyTests.cs, src/FLEx-ChorusPluginTests/Infrastructure/Handling/LoadHandlersTests.cs, src/FLEx-ChorusPluginTests/Integration/MergeIntegrationTests.cs, src/FLEx-ChorusPluginTests/TestData/Language Explorer/Configuration/DictionaryConfiguration.xsd, src/TriboroughBridge-ChorusPlugin/Utilities.cs
Use file-as-atom merge strategy.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/69)
=> LT-16773: S/R New Configs: Implement Merge Step

src/FLEx-ChorusPluginTests/Infrastructure/Handling/ConfigLayout/DictionaryConfigurationHandlerStrategyTests.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/70)
=> Fix Failing Unit Tests

DistFiles/localizations/Palaso.en.tmx, DistFiles/localizations/Palaso.es.tmx, DistFiles/localizations/Palaso.fr.tmx, DistFiles/localizations/Palaso.zh-Hans.tmx
* Update the version of the Palaso.dll to current to
avoid 'Preparing User Interface for Localizations' step
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/71)
=> Fix LT-16918 by avoiding unnecessary update

debian/control
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/75)
=> Update build dependencies for Ubuntu 16.04/xenial

ReadMe.md, debian/changelog, src/Installer/Alpha.htm, src/Installer/ReleaseNotes.md
[<img src="https://reviewable.io/review_button.png" height=80 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/74)
=> Update Release Notes and Instructions

src/FLEx-ChorusPlugin/Infrastructure/ActionHandlers/SendReceiveActionHandler.cs
* Make sure existing Temp xsd file doesn't get in the way
* Make sure we clean up after ourselves when we're done
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/80)
=> LT-16969 even better

src/FLEx-ChorusPlugin/Infrastructure/Handling/ConfigLayout/DictionaryConfigurationHandlerStrategy.cs
* GetXsdPath exception
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/81)
=> More exception info

src/FLEx-ChorusPlugin/Infrastructure/ActionHandlers/SendReceiveActionHandler.cs, src/FLEx-ChorusPlugin/Infrastructure/Handling/ConfigLayout/DictionaryConfigurationHandlerStrategy.cs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/83)
=> Put responsibility for xsd location back on FLEx

src/FLEx-ChorusPluginTests/Infrastructure/ActionHandlers/FlexObtainProjectStrategyTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/94)
=> Refactor FlexObtainProjectStrategyTests

src/FLEx-ChorusPlugin/Infrastructure/Handling/ConfigLayout/CustomLayoutMergeService.cs, src/FLEx-ChorusPluginTests/Infrastructure/Handling/Linguistics/Lexicon/FieldWorksLexiconTypeHandlerTests.cs
* Adjust to new Merge interface method
* Add new unit test for a bug (that was fixed in Chorus)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/98)
=> Adjust to change in Chorus interface for fix LT-17461

src/FLEx-ChorusPlugin/Infrastructure/DomainServices/FLExProjectSplitter.cs, src/FLEx-ChorusPlugin/Infrastructure/MetadataCache.cs, src/FLEx-ChorusPluginTests/Integration/UpdateMetaDataCacheTests.cs
* Upgrade MetaDataCache to version 69 with tests
* Add some improved exception messages to help future
maintainers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/103)
=> Enable support for DM69 model

src/FLEx-ChorusPluginTests/Infrastructure/Handling/ReportsByDataType/OwningAtomicDataTypeReportTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/108)
=> Fix a unit test broken by the model change

build/FLExBridge.build.mono.proj, debian/control, debian/rules
By cherry-picking some commits from master. Include a cherry-pick about how FB's package architecture is specified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/110)
=> Fix Dictionary branch to build on Ubuntu 16.04 xenial

build/NuGet.targets
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/111)
=> Cherry pick nuget fix from master

Makefile, download_dependencies_linux.sh, download_dependencies_windows.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/112)
=> Cherry pick more fixes, for packaging

src/FLEx-ChorusPlugin/Contexts/Linguistics/Lexicon/LexiconBoundedContextService.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/117)
=> Add nesting of Languages, DialectLabels and ExtendedNoteTypes

src/FLEx-ChorusPlugin/Infrastructure/MetadataCache.cs, src/FLEx-ChorusPluginTests/FieldWorksTestServices.cs, src/FLEx-ChorusPluginTests/Infrastructure/Handling/BaseFieldWorksTypeHandlerTests.cs, src/FLEx-ChorusPluginTests/Infrastructure/Handling/ConfigLayout/DictionaryConfigurationHandlerStrategyTests.cs, src/FLEx-ChorusPluginTests/Integration/MergeIntegrationTests.cs, src/FLEx-ChorusPluginTests/Integration/UpdateMetaDataCacheTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/116)
=> Fix FB model to match FW model; Reinforce Unit Tests

update-version
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/62)
=> Add update-version script

download_dependencies_linux.sh, download_dependencies_windows.sh
* Tags for FW-8.3.1
* Include PalasoUIWindowsForms.dll.config
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/122)
=> Update DownloadDependencies Scripts

DistFiles/localizations/Chorus.en.tmx, DistFiles/localizations/FlexBridge.en.tmx, Makefile, run-flexbridge
Update Chorus.en.tmx and FlexBridge.en.tmx files.
Add run-flexbidge to load environ and copy localizations to
.local/share/SIL/FlexBridge/localizations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/121)
=> Fix localizations crash

src/LibFLExBridge-ChorusPlugin/Handling/ConfigLayout/DictionaryConfigurationHandlerStrategy.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/128)
=> Fix failing test on TC

build/NuGet.targets
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/132)
=> Fix for Ubuntu 16.04 packaging

build/NuGet.targets
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/133)
=> Move nuget setting to a more appropriate place

.gitignore, src/FLEx-ChorusPlugin/FLEx-ChorusPlugin.csproj, src/FLEx-ChorusPlugin/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/134)
=> Get icu.net from nuget package

src/FLEx-ChorusPlugin/Infrastructure/MetadataCache.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/135)
=> DM70 (no-op)

src/FLEx-ChorusPlugin/Infrastructure/FlexFolderSystem.cs
* Include ConfigurationSettings/**Overrides.css in Send/Receive
* Alphabetize excluded extensions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/140)
=> SendReceive User CSS Overrides

src/FLEx-ChorusPlugin/Infrastructure/Handling/ConfigLayout/DictionaryConfigurationHandlerStrategy.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/141)
=> Virtualstore

src/FLEx-ChorusPluginTests/TestData/DataNotebook_Ann.ntbk, src/FLEx-ChorusPluginTests/TestData/DataNotebook_Common.ntbk, src/FLEx-ChorusPluginTests/TestData/DataNotebook_Susanna.ntbk, src/LibFLExBridge-ChorusPlugin/Handling/PreferMostRecentTimePreMerger.cs, src/LibFLExBridge-ChorusPluginTests/Handling/BaseFieldWorksTypeHandlerTests.cs
Always output three-digit milliseconds to prevent a crash in FLEx.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/143)
=> Fix DateModified format

src/FLEx-ChorusPlugin/Infrastructure/Handling/ConfigLayout/DictionaryConfigurationHandlerStrategy.cs, src/FLEx-ChorusPluginTests/Integration/MergeIntegrationTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/146)
=> Fix validation after merge namespace issue

download_dependencies_linux.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/147)
=> Update master branch linux download script for TeamCity changes

download_dependencies_linux.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/148)
=> Update Dictionary branch linux download script for TeamCity change

DistFiles/localizations/Chorus.en.tmx, DistFiles/localizations/FlexBridge.en.tmx, DistFiles/localizations/Palaso.en.tmx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/150)
=> LT-18453 Update .tmx files to latest

build/FLExBridge.build.win.proj, build/TestInstallerBuild.bat, src/FLExBridge/app.config, src/FLExBridge/packages.config, src/Installer/Installer.wixproj, src/Installer/Installer.wxs
*Worked in master branch
*Adjusted the related settings for the latest configuration.
*Change the FLEX Bridge version number as 9.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/152)
=> Fix LT-16680: Send Receive menu unavailable while FLExBridge installed

build/FLExBridge.build.win.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/159)
=> Update name of unzip task

.gitignore, build/FLExBridge.build.win.proj, download_dependencies_windows.sh
- Include .msm dependencies
- Unzip depends on Restore packages
- Adjust location of buildtasks
- Change solution name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/160)
=> Update Installer build

build/FLExBridge.build.win.proj, src/Installer/Installer.wxs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/161)
=> Updated files that were missed in the previous commit

src/CommonAssemblyInfo.cs, src/Installer/Installer.wxs
- Rename a component and add a missing component
- use UTF-8 for copyright symbol
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/162)
=> LT-18673 Fix Clicking on S/R menus leads to crash

src/LiftBridge-ChorusPlugin/Infrastructure/ActionHandlers/ObtainProjectStrategyLift.cs
Adjust floating point number parsing to be culture independent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/163)
=> LT-18624 Accommodate number formats for other cultures

src/LibFLExBridge-ChorusPlugin/Infrastructure/ActionHandlers/ObtainProjectStrategyFlex.cs, src/LibFLExBridge-ChorusPlugin/Infrastructure/ActionHandlers/SendReceiveActionHandler.cs, src/LibFLExBridge-ChorusPlugin/Infrastructure/ActionHandlers/UndoExportActionHandler.cs, src/LibFLExBridge-ChorusPlugin/Infrastructure/ActionHandlers/ViewNotesActionHandler.cs, src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSynchronizerAdjunct.cs, src/LibFLExBridge-ChorusPlugin/Infrastructure/MetadataCache.cs, src/LibFLExBridge-ChorusPlugin/LibFLExBridge-ChorusPlugin.csproj, src/TriboroughBridge-ChorusPlugin/Infrastructure/ActionHandlers/ActionTypeHandlerRepository.cs
- Add ActionHandlers for send/receive to FlexBridge
- Update the model number to handle 700071
- Add SynchronizerAdjunct code to build
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/164)
=> LT-18673 Click on S/R menus leads to crash pt2

src/LibTriboroughBridge-ChorusPlugin/Infrastructure/UpdateBranchHelper.cs, src/LiftBridge-ChorusPlugin/Infrastructure/UpdateBranchHelperLift.cs, src/TriboroughBridge-ChorusPlugin/CommandLineProcessor.cs
* Perform LIFT imports and send/receive on 0.13_ldml3 branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/171)
=> LT-18674 Migrate .ldml to v3 and update branch to 0.13_ldml3

download_dependencies_linux.sh, download_dependencies_windows.sh, src/FLEx-ChorusPlugin/FLEx-ChorusPlugin.csproj, src/FLEx-ChorusPluginTests/FLEx-ChorusPluginTests.csproj, src/FLExBridge/FLExBridge.csproj, src/FwdataNester/FwdataTestApp.csproj, src/LfMergeBridge/LfMergeBridge.csproj, src/LfMergeBridgeTestApp/LfMergeBridgeTestApp.csproj, src/LibFLExBridge-ChorusPlugin/LibFLExBridge-ChorusPlugin.csproj, src/LibFLExBridge-ChorusPluginTests/LibFLExBridge-ChorusPluginTests.csproj, src/LibTriboroughBridge-ChorusPlugin/LibTriboroughBridge-ChorusPlugin.csproj, src/LiftBridge-ChorusPlugin/LiftBridge-ChorusPlugin.csproj, src/LiftBridge-ChorusPluginTests/LiftBridge-ChorusPluginTests.csproj, src/LiftFileCheckerApp/LiftFileCheckerApp.csproj, src/RepositoryUtility/RepositoryUtility.csproj, src/TriboroughBridge-ChorusPlugin/TriboroughBridge-ChorusPlugin.csproj, src/TriboroughBridge-ChorusPluginTests/TriboroughBridge-ChorusPluginTests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/175)
=> Update to .Net 4.6.1

ReadMe.md
This is simple, but after having enough trouble building from commandline, having an instruction that says, "This is how to do it, build this solution from VS", is perhaps helpful.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/176)
=> Add build instructions

build/WixPatchableInstaller.targets, build/build.bat, src/InstallerOverrides/Overrides.wxi
* Copy Mercurial to the directory harvested by the installer
* Exclude test code and the RepositoryUtility from this copy
* Write to the registry key FLEx expects
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/178)
=> Make Installer Work

src/InstallerOverrides/Overrides.wxi
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/180)
=> Remove conflicting property

debian/rules
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/182)
=> Fix package build

build/FLExBridge.proj, build/WixPatchableInstaller.targets, download_dependencies_windows.sh, src/Installer/TODO.xml, src/InstallerOverrides/CustomFeatures.wxi, src/InstallerOverrides/Overrides.wxi
* Some organization
* Install L10n files
* Include ChorusMerge merge module
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/181)
=> Make FLEx Bridge installer work

download_dependencies_windows.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/184)
=> Include SIL.WritingSystems (needed for LIFT)

src/LibFLExBridge-ChorusPluginTests/Handling/Linguistics/FieldWorksFeatureSystemTypeHandlerTests.cs
Merging child nodes in Features should not duplicate children
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/183)
=> Add test for feature system merges

ReadMe.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/188)
=> Add to instructions

src/FLEx-ChorusPlugin/Infrastructure/ActionHandlers/ObtainProjectStrategyFlex.cs, src/LibTriboroughBridge-ChorusPlugin/Infrastructure/UpdateBranchHelper.cs
* Fix issue with the empty repository fix
* Clean up some whitespace
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/191)
=> Clean up after 18788

flexbridge
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/193)
=> Fix geckofx crash on development machine

Makefile, debian/control
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/194)
=> Follow-up of previous commit

src/LibFLExBridge-ChorusPlugin/Infrastructure/MetadataCache.cs, src/LibFLExBridge-ChorusPluginTests/Integration/UpdateMetaDataCacheTests.cs
*Added code to remove ReversalEntries property in LexSense
*Added code to add Senses property in ReversalIndexEntry
*Updated the ModelVersion number
*Added the test case for this case
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/200)
=> Fix LT-18918:Update FlexBridge to support new DataModel

FLExBridge.sln, build/NuGet.targets, build/nuget-common/packages.config, build/nuget-linux/packages.config, build/nuget-windows/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/203)
=> Download GeckoFX 45 from NuGet on Linux platforms

src/LfMergeBridge/SerializableLfComment.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/202)
=> Add ContextGuid property (LF-48)

build/FLExBridge.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/208)
=> LT-18916 Copy GeckoBrowserAdapter to output folder on Linux

environ-xulrunner
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/209)
=> Fix syntax for sh, and too many brackets

download_dependencies_linux.sh, download_dependencies_windows.sh, src/FLExBridge/FLExBridge.csproj, src/LibFLExBridge-ChorusPlugin/LibFLExBridge-ChorusPlugin.csproj, src/RepositoryUtility/RepositoryUtility.csproj, src/TriboroughBridge-ChorusPlugin/TriboroughBridge-ChorusPlugin.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/214)
=> Update dependencies and reference to SIL.Reporting

Makefile, build/nuget-linux/packages.config, environ-xulrunner, src/FLExBridge/FLExBridge.csproj, src/RepositoryUtility/RepositoryUtility.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/221)
=> Update geckofx45 to match Linux FW

Makefile, build/nuget-linux/packages.config, environ-xulrunner, src/FLExBridge/FLExBridge.csproj, src/RepositoryUtility/RepositoryUtility.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/223)
=> Update geckofx45 for Linux to 45.0.36 to work on trusty

Makefile, build/nuget-linux/packages.config, debian/changelog, environ, environ-xulrunner, src/FLExBridge/FLExBridge.csproj, src/Installer/ReleaseNotes.md, src/Installer/Stable.htm, src/RepositoryUtility/RepositoryUtility.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/224)
=> Merge master to develop

lib/common/run-app
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/228)
=> Fix Chorushub

build/FLExBridge.proj
Download nuget.exe before trying to use it :-).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/233)
=> Add dependency to RestoreBuildTasks

build/FLExBridge.proj, src/LibFLExBridge-ChorusPluginTests/Handling/BaseFieldWorksTypeHandlerTests.cs, src/LibFLExBridge-ChorusPluginTests/Handling/DateTimeMergingTests.cs, src/LibFLExBridge-ChorusPluginTests/Handling/Linguistics/Lexicon/FieldWorksLexiconTypeHandlerTests.cs, src/LibFLExBridge-ChorusPluginTests/Handling/PreferMostRecentTimePreMergerTests.cs
This allows to use mono 3 which looks like it's needed on TC for
running the tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/234)
=> Allow to ignore import of GitVersionTask.targets file

src/InstallerOverrides/Overrides.wxi
* Need to set Default AppFolder Directory when it run quite mode
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/237)
=> Fix: LT-19303 FLEx Bridge should install under Progra

Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/241)
=> Use msbuild in Makefile

src/TriboroughBridge-ChorusPlugin/TriboroughBridgeUtilities.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/243)
=> Update to new L10NSharp API

ReadMe.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/244)
=> Update Windows build instructions in ReadMe.md

.gitignore, UpdateDependencies.bat, UpdateDependencies.sh, build/FLExBridge.proj, download_dependencies_linux.sh, download_dependencies_windows.sh, src/FLEx-ChorusPlugin/FLEx-ChorusPlugin.csproj, src/FLEx-ChorusPlugin/packages.config, src/FLExBridge/FLExBridge.csproj, src/FLExBridge/app.config, src/FLExBridge/packages.config, src/FwdataNester/FwdataTestApp.csproj, src/FwdataNester/packages.config, src/Installer/Installer.wxs, src/LiftBridge-ChorusPlugin/LiftBridge-ChorusPlugin.csproj, src/LiftBridge-ChorusPlugin/packages.config, src/RepositoryUtility/RepositoryUtility.csproj, src/RepositoryUtility/packages.config, src/TriboroughBridge-ChorusPlugin/TriboroughBridge-ChorusPlugin.csproj, src/TriboroughBridge-ChorusPlugin/packages.config
We'll still have to remove the dependencies from TC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/242)
=> Use nuget packages for L10NSharp and HelpProvider

src/TriboroughBridge-ChorusPlugin/FLExConnectionHelper.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/249)
=> Fix jump url crash (LT-19036)

Makefile, build/FLExBridge.proj
Also update GitVersion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/253)
=> Fix Linux package build

GitVersion.yml, ReadMe.md, debian/changelog, src/Installer/Beta.htm, src/Installer/ReleaseNotes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/256)
=> Update release with Chorus bugfix, bump version to 3.1.1

GitVersion.yml, build/WixPatchableInstaller.targets, debian/changelog, src/Installer/Beta.htm, src/Installer/ReleaseNotes.md
* Includes chorus bugfix for LT-20074
* Includes updated GenericInstaller (maybe new icons)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/257)
=> Update to version 3.1.2

Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/260)
=> Escape $, fixing Makefile syntax for python2

Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/261)
=> Make release check sh compatible, fixing syntax, for python2

Makefile, debian/control
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/262)
=> Change python2 hack to less intrusive, shared package

DistFiles/localizations/Chorus.es.tmx, DistFiles/localizations/Chorus.fr.tmx, DistFiles/localizations/Chorus.zh-CN.tmx, DistFiles/localizations/FlexBridge.es.tmx, DistFiles/localizations/FlexBridge.fr.tmx, DistFiles/localizations/FlexBridge.zh-CN.tmx, DistFiles/localizations/Palaso.es.tmx, DistFiles/localizations/Palaso.fr.tmx, DistFiles/localizations/Palaso.zh-CN.tmx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/258)
=> Groom TMX Files for Crowdin

environ
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/266)
=> Fix indentation in environ

l10n/l10n.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/269)
=> Fix typo DepondsOnTargets

Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/270)
=> Add fetching localizations to Linux packaging steps

l10n/l10n.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/272)
=> Update to latest library l10ns and Normalize FieldWorksL10ns

debian/control
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/273)
=> Update dependency name python-is-python2

debian/control
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/274)
=> Add build dependency dotnet-sdk-3.1

GitVersion.yml, ReadMe.md, build/WixPatchableInstaller.targets, debian/changelog, src/Installer/Beta.htm, src/Installer/ReleaseNotes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/276)
=> Bump version to 3.1.4

FLExBridge.sln.DotSettings, l10n/l10n.proj, src/TriboroughBridge-ChorusPlugin/TriboroughBridgeUtilities.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/279)
=> Install XLF L10ns on Linux

Makefile
:facepalm:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/281)
=> Apply AutoGenerateBindingRedirects LT-20123 fix to release build

GitVersion.yml, debian/changelog, src/Installer/Beta.htm, src/Installer/ReleaseNotes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/284)
=> Bump version up to 3.1.5

src/FLEx-ChorusPlugin/packages.config, src/FwdataNester/FwdataTestApp.csproj, src/FwdataNester/packages.config, src/LiftBridge-ChorusPlugin/LiftBridge-ChorusPlugin.csproj, src/LiftBridge-ChorusPlugin/packages.config, src/TriboroughBridge-ChorusPlugin/TriboroughBridge-ChorusPlugin.csproj, src/TriboroughBridge-ChorusPlugin/packages.config
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/286)
=> Update HelpProvider to the latest

build/WixPatchableInstaller.targets
Generate a new Product ID GUID for version 3.1.5.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/287)
=> Bump version to 3.1.5 (GUID)

GitVersion.yml, build/WixPatchableInstaller.targets, debian/changelog, src/Installer/Beta.htm, src/Installer/ReleaseNotes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/288)
=> Bump version to 3.1.6

build/FLExBridge.proj, src/FLEx-ChorusPlugin/Infrastructure/ActionHandlers/ViewNotesActionHandler.cs, src/FLExBridge/Program.cs, src/LibFLExBridge-ChorusPlugin/DomainServices/FieldWorksMergeServices.cs, src/LibFLExBridge-ChorusPlugin/Handling/FwLinkArgs.cs, src/LiftBridge-ChorusPlugin/Infrastructure/ActionHandlers/ViewNotesLiftActionHandler.cs, src/RepositoryUtility/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/290)
=> Add default target and replace deprecated method calls

FLExBridge.sln.DotSettings, src/TriboroughBridge-ChorusPlugin/TriboroughBridgeUtilities.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/292)
=> Update localization email address

ReadMe.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/297)
=> doc: Needs Ubuntu 18.04

GitVersion.yml, build/FLExBridge.proj, build/WixPatchableInstaller.targets, debian/changelog, src/Installer/ReleaseNotes.md, src/Installer/Stable.htm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/296)
=> Bump version to 3.1.8

src/FLEx-ChorusPluginTests/FLEx-ChorusPluginTests.csproj, src/FLExBridge/FLExBridge.csproj, src/LfMergeBridge/LfMergeBridge.csproj, src/LibFLExBridge-ChorusPlugin/LibFLExBridge-ChorusPlugin.csproj, src/LibFLExBridge-ChorusPluginTests/LibFLExBridge-ChorusPluginTests.csproj, src/LibTriboroughBridge-ChorusPlugin/LibTriboroughBridge-ChorusPlugin.csproj, src/LiftBridge-ChorusPlugin/LiftBridge-ChorusPlugin.csproj, src/LiftBridge-ChorusPluginTests/LiftBridge-ChorusPluginTests.csproj, src/TriboroughBridge-ChorusPlugin/TriboroughBridge-ChorusPlugin.csproj, src/TriboroughBridge-ChorusPluginTests/TriboroughBridge-ChorusPluginTests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/301)
=> Update to current Chorus version

src/FLEx-ChorusPlugin/FLEx-ChorusPlugin.csproj, src/FLEx-ChorusPluginTests/FLEx-ChorusPluginTests.csproj, src/FLExBridge/FLExBridge.csproj, src/FwdataNester/FwdataTestApp.csproj, src/LfMergeBridge/LfMergeBridge.csproj, src/LfMergeBridgeTests/LfMergeBridgeTests.csproj, src/LibFLExBridge-ChorusPlugin/LibFLExBridge-ChorusPlugin.csproj, src/LibFLExBridge-ChorusPluginTests/LibFLExBridge-ChorusPluginTests.csproj, src/LibTriboroughBridge-ChorusPlugin/LibTriboroughBridge-ChorusPlugin.csproj, src/LiftBridge-ChorusPlugin/LiftBridge-ChorusPlugin.csproj, src/LiftBridge-ChorusPluginTests/LiftBridge-ChorusPluginTests.csproj, src/RepositoryUtility/RepositoryUtility.csproj, src/TriboroughBridge-ChorusPlugin/TriboroughBridge-ChorusPlugin.csproj, src/TriboroughBridge-ChorusPluginTests/TriboroughBridge-ChorusPluginTests.csproj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/302)
=> Use the latest versions of all SIL NuGet packages

debian/changelog, src/Installer/Beta.htm, src/Installer/ReleaseNotes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/305)
=> Update Release Notes

build/WixPatchableInstaller.targets, debian/changelog, src/Installer/Alpha.htm, src/Installer/ReleaseNotes.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/309)
=> +semver:patch

debian/control, environ, flexbridge
Use the environment variables provided by FieldWorks
without modification.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/311)
=> Fix Crashes on Linux

.gitignore, build/FLExBridge.dep, build/FLExBridge.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/320)
=> Download Chorus_Help.chm during build

appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/325)
=> Fix gitversion on appveyor for non-PR builds

Makefile, build/FLExBridge.proj, debian/control, debian/postinst, debian/prerm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/326)
=> Fix packaging

appveyor.yml, build/FLExBridge.proj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/327)
=> Another attempt to fix non-PR appveyor builds
