- build/Download.targets
- debian/control
* Use the pinned and tagged icu40 build from TC
* Change suggests to require for fieldworks and restrict
the maximum version.
> Update flexbridge Beta to work with tagged ICU build

- debian/control
posinst requires unzip to unpack mercurial.
> Add unzip to binary dependency

- src/Installer/Installer.wxs
* Chorus files had an apparent downgrade for 2.3, their version
numbers should be bumped up but this change fixes the issue
permanantly
> Fix LT-16314: Invalid installation after upgrade from 2.2.15

- build/FLExBridge.build.win.proj
- src/Installer/Installer.wxs
The Chorus merge module will not function correctly if the Schedule
attribute is anything but afterInstallValidate
* Reset 'Schedule' to afterInstallValidate
* Add DevelopInstaller target and comment for how to validate installer
work on a developer machine
> Revert the Schedule attribute change and add dev target

- debian/postinst
The plugin is required on linux after the upgrade to mercurial 3
in order to handle integer only branch names.
> Add the fixutf8 plugin to Mercurial.ini in postinst

- build/FLExBridge.build.mono.proj
* The shortcut had not yet been removed and we don't have a package
for ChorusHub yet. So until we can make one include ChorusHub.exe
so that the shortcut will launch the service.
> Install ChorusHub on linux until a separate package is created

- Makefile
- ReadMe.md
- build/FLExBridge.build.win.proj
- build/build.common.proj
- src/Installer/Alpha.htm
- src/Installer/ReleaseNotes.md
- src/Installer/appcast.xml
- src/Installer/index.htm
- src/TriboroughBridge-ChorusPlugin/Infrastructure/ActionHandlers/CheckForUpdatesActionTypeHandler.cs
* Update Alpha.htm and ReleaseNotes.md with some historical information
* Update the ReadMe.md with release instructions
* Update the Makefile to generate the right version number
* Update the build.common.proj even though it isn't necessary
* Update the appcast.xml so that the next Alpha release should be
offered to users automatically.
* Update the index.html to offer information about both Beta and Alpha
releases
> Update release documentation, increase version to 2.3.9

- build/build.common.proj
* Becuase Palaso.BuildTasks.dll is adds build tasks to msbuild
it needs to be present in version control.
* To perform some tasks MarkdownDeep.dll is needed, but we can
use NuGet to grab it and copy it next to Palaso.BuildTasks.dll
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/61)
> Modify the PrepareForPublishing target to retrieve MarkdownDeep

- src/FLEx-ChorusPlugin/Infrastructure/ActionHandlers/SendReceiveActionHandler.cs
* Make sure Temp folder exists
* After copying xsd file, make sure it's not read-only
(which would interfere with copying it again later)
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/78)
> LT-16969 second sync crash

- Makefile
- build/FLExBridge.build.mono.proj
- build/NuGet.targets
- debian/control
- debian/copyright
- debian/rules
- download_dependencies_linux.sh
- download_dependencies_windows.sh
The main purpose is to switch to using automatic dependency generation, but a few other things are tidied up in the process. In particular, the package now builds successfully for 16.04 (Xenial).
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/79)
> Update Linux packaging

- src/Installer/Installer.wxs
When the first three version numbers and the Upgrade Code match,
but the Prouct Code does not, MSI allows installing both versions
as "separate products." This is not good. AllowSameVersionUpgrades
interprets installing these "same versions" as an "upgrade,"
therefore properly removing the installed version before installing.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/86)
> LT-17100: Uninstall FLExBridge before installing

- build/FLExBridge.build.win.proj
- build/build.common.proj
- src/Installer/Installer.wxs
Changes in FLExBridge code:
- If the Version Property is set, use it; otherwise, read from the
Version file
- Update instructional comment on DevelopInstaller target
- Revert AllowSameVersionUpgrades
Changes in TeamCity:
- set `system.Version=2.4.%build.counter%`
- set Build number format: `%system.Version%.{build.vcs.number.1}`
[<img src="https://reviewable.io/review_button.svg" height="20" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/87)
> Allow Passing Version to the Installer Builder as a Property

- src/LfMergeBridge/LanguageForgeMakeCloneActionHandler.cs
- src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs
- src/LfMergeBridge/LanguageForgeUpdateToLongHashActionHandler.cs
- src/LfMergeBridge/LfMergeBridgeUtilities.cs
This also tweaks some messages being sent back to
the LF merge client.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/96)
> Remove code from LF Bridge that is now in Chorus

- src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs
When running tests in LfMerge we use a directory rather than a remote URL, so we need to create the proper RepositoryAddress which the Create() method takes care of.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/97)
> Use RepositoryAddress.Create to create repo path

- src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs
- src/LibFLExBridge-ChorusPlugin/Handling/MultiLingualStringsContextGenerator.cs
This fixes the problem in LfMergeBridge where changes we got from
others didn't show up in LanguageForge because the working directory
didn't get updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/101)
> Update working directory after pulling changes

- Makefile
flexbridge is packaged as an any architecture package. So since it
bundles Mercurial, it needs to bundle both Mercurial architectures so
it can run on machines of either architecture.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/104)
> Include all architectures of mercurial

- src/FLEx-ChorusPlugin/Infrastructure/DomainServices/CmObjectValidator.cs
- src/FLEx-ChorusPluginTests/Infrastructure/DomainServices/CmObjectValidatorTests.cs
* There is a bug in FLEx somewhere that lets the user create a Run
with a bad attribute. Tracking down what the attribute was lead
to the desire for this fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/120)
> Improve error messages for invalid attributes in CmObjects

- src/LfMergeBridge/LanguageForgeMakeCloneActionHandler.cs
- src/LfMergeBridge/LfMergeBridgeUtilities.cs
Let LfMerge deal with deleting repo if the desired branch doesn't
exist. This allows to support multiple database model version
without having to re-clone the repo. The change is backwards
compatible; unless the new option "deleteRepoIfNoSuchBranch" is set
to false nothing will change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/119)
> [LfMergeBridge] Don't delete repo if no such branch

- Makefile
Execute previous environ during make release/debug, instead of updated
run-in-environ file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/125)
> Change makefile to use previous environ

- DistFiles/localizations/Chorus.en.tmx
- DistFiles/localizations/Chorus.es.tmx
- DistFiles/localizations/Chorus.fr.tmx
- DistFiles/localizations/Chorus.zh-Hans.tmx
- Makefile
- flexbridge
- run-in-environ
Change execution script from run-in-environ to flexbridge.
Keep run-in-environ for developer purposes.
Cleanup Makefile to include the flexbridge file.
Update Chorus*.tmx localization files to version 2.5.1068.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/126)
> Change FB execution script for linux

- flexbridge
To make sure we run the right mono without relying on binfmt choosing
the right one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/129)
> Specify mono when executing FLExBridge.exe

- src/LfMergeBridge/LfMergeBridge.cs
If Mercurial is not set up properly, pass Mercurial's error message on to the client so the client can figure out what to do about it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/138)
> Don't suppress Mercurial readiness error message

- src/LfMergeBridge/LfMergeBridge.cs
The `actionType` string isn't a key into the `options` dictionary.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/139)
> Fix "unknown action type" error message

- src/LibFLExBridge-ChorusPlugin/Handling/PreferMostRecentTimePreMerger.cs
- src/LibFLExBridge-ChorusPluginTests/Handling/BaseFieldWorksTypeHandlerTests.cs
- src/LibFLExBridge-ChorusPluginTests/Handling/DateTimeMergingTests.cs
- src/LibFLExBridge-ChorusPluginTests/Handling/Linguistics/Lexicon/FieldWorksLexiconTypeHandlerTests.cs
- src/LibFLExBridge-ChorusPluginTests/Handling/PreferMostRecentTimePreMergerTests.cs
- src/LibFLExBridge-ChorusPluginTests/LibFLExBridge-ChorusPluginTests.csproj
This fixes a problem when doing S/R in LanguageForge. LF relies on the DateModified time stamp to know which entries it needs to process. If an entry got modified in FLEx and the same entry but
different field got modified in LF, the S/R merged the changes but set the DateModified field to the newer date (which was from LF). This caused LF not to re-process the entry because it already
processed the entry with that time stamp. This caused the modified data from FLEx to not show up in LF (https://trello.com/c/UoyXj4jP).
This change fixes this problem by setting DateModified to the current time in case of a merge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/137)
> Update DateModified when doing a merge

- src/LfMergeBridge/LanguageForgeGetChorusNotesActionHandler.cs
- src/LfMergeBridge/LanguageForgeWriteToChorusNotesActionHandler.cs
- src/LfMergeBridge/LfMergeBridge.csproj
- src/LfMergeBridge/LfMergeBridgeUtilities.cs
- src/LfMergeBridge/SerializableLfAuthorInfo.cs
- src/LfMergeBridge/SerializableLfComment.cs
- src/LfMergeBridge/SerializableLfCommentRegarding.cs
- src/LfMergeBridge/SerializableLfCommentReply.cs
- src/LfMergeBridge/packages.config
- src/LibTriboroughBridge-ChorusPlugin/ActionType.cs
- src/LibTriboroughBridge-ChorusPlugin/Infrastructure/ActionHandlers/StringToActionTypeConverter.cs
This PR needs to be merged before the corresponding LfMerge PR is merged, since LfMerge will depend on having an LfMergeBridge DLL that knows the new GetChorusNotes and WriteToChorusNotes actions.
There are no unit tests yet, but I'm creating the PR anyway so that we can kick off a TeamCity build and make sure that it compiles.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/149)
> Send/Receive Chorus Notes with LF comments

- build/FLExBridge.build.win.proj
- build/TestInstallerBuild.bat
- src/Installer/Installer.wxs
*Updated the setting for FLExBridge
*Changed the FLExBridge version number to 9 for registry
*Removed unused Palaso related files.
*Included SIL related files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/153)
> LT-16680:Send Receive menu unavailable while FLExBridge installed

- build/FLExBridge.build.win.proj
The MsBuild.Community.Tasks.Targets file is unavailable until it has been NuGotten.
- Restore NuGet packages first (TC Config)
- Import the .Targets file only if it exists
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/157)
> Fix TeamCity Builds (NuGet)

- build/FLExBridge.proj
* Starting on Oct 10 anything output stderr failed a build
This avoids 'plugin loaded...' messages that were being
output to stderr in the build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/174)
> Use the NUnitTeamCity task when running on TC

- src/LfMergeBridge/LanguageForgeWriteToChorusNotesActionHandler.cs
Chorus status of "note" is used for things like conflict reports, etc.; anything created by users in FLEx has the status of "question", and LF comments should be the same.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/179)
> LF comments become questions rather than notes

- build/FLExBridge.proj
And arrange so the right one gets called depending on the OS.
The CopyExtraFilesToOutput target was getting skipped on Linux,
resulting in localization files not being copied.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/189)
> Split CopyExtraFiles target name by OS

- debian/rules
MAPI32.DLL was Windows-only in MAPIHelper.cs before #if !MONO was
removed.
__Internal probably should have been ignored by dh_clideps without us
having to say so. This is in Platform.cs.
This fixes a Linux packaging error.
Both Platform.cs and MAPIHelper.cs are in libpalaso, and this problem
was introduced to flexbridge packaging when we switched to use the
master branch of libpalaso.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/190)
> Ignore problematic DllImport references

- src/LfMergeBridge/LanguageForgeWriteToChorusNotesActionHandler.cs
- src/LfMergeBridgeTests/LanguageForgeWriteToChorusNotesActionHandlerTests.cs
If we have an empty statusGuid but have a comment on both LD and LF
it means that we did a s/r before we introduced the statusGuid. Any
status change is assumed to have happened on LD, otherwise the s/r
would have set the statusGuid.
This change also switches the expected and actual values in the
calls to AssertThatXmlIn.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/201)
> Fix handling of empty statusGuid

- src/LfMergeBridge/LanguageForgeCommitAuxiliaryActionHandler.cs
- src/LfMergeBridge/LanguageForgeGetChorusNotesActionHandler.cs
- src/LfMergeBridge/LanguageForgeWriteToChorusNotesActionHandler.cs
- src/LfMergeBridgeTests/LanguageForgeGetChorusNotesActionHandlerTests.cs
- src/LfMergeBridgeTests/LanguageForgeWriteToChorusNotesActionHandlerTests.cs
- src/LfMergeBridgeTests/LfMergeBridgeTests.csproj
- src/LfMergeBridgeTests/NotesTestHelper.cs
We want to make sure that the statusGuid gets set when we get the
chorus notes prior to importing them into Mongo. This is necessary
so that we can detect on which side (LF or FLEx) a status change
happened.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/207)
>  [LfMergeBridge] Set StatusGuid when getting notes 

- build/WixPatchableInstaller.targets
- src/CommonAssemblyInfo.cs
our only client should be the FLEx installer, which downloads
our artifacts from what it expects to be a stable URL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/215)
> Remove version numbers from installer artifacts

- debian/control
Getting geckofx45 build dependency from nuget
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/219)
> Remove geckofx29 build-depend

- src/FLEx-ChorusPlugin/FLEx-ChorusPlugin.csproj
- src/FLExBridge/FLExBridge.csproj
Use geckofx45 not 29.
Remove unneeded geckofx reference from FLEx-ChorusPlugin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/217)
> Fix geckofx usage in csproj

- src/LfMergeBridge/LanguageForgeGetChorusNotesActionHandler.cs
- src/LfMergeBridgeTests/LanguageForgeWriteToChorusNotesActionHandlerTests.cs
Some annotations in real user data have NO `<message>` elements inside them, which causes the merge to fail and the project to be put on hold. This is not *supposed* to happen, but it does, so we need to deal with it. This commit is the simplest way I've found to do so: it skips any such annotations, because we can't extract any meaningful data from them anyway (and trying to do so ends up causing other issues).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/220)
> Fix bug when annotations contained no messages

- DistFiles/about.htm
* Added Chorus Hub download link in about.htm.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/226)
> Fix LT-19080: Add Chorus Hub download link in about.htm

- build/FLExBridge.proj
- build/WixPatchableInstaller.targets
- src/InstallerOverrides/CustomFeatures.wxi
- src/InstallerOverrides/Redistributables.wxi
* Install VC redists for only 10,11,12
* Include shorcuts in an unavailable feature to appease ICE
* Unzip $(Configuration)\Mercurial.zip to fix release builds
* Update Wix Installer repo (many patch-related fixes)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/229)
> Prepare for Patching

- src/LfMergeBridgeTests/LfMergeBridgeTests.csproj
This change allows FLExBridge to compile with libpalaso version >= 5.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/238)
> Fix Linux build

- .gitignore
- src/LfMergeBridge/LanguageForgeWriteToChorusNotesActionHandler.cs
- src/LfMergeBridgeTests/LanguageForgeWriteToChorusNotesActionHandlerTests.cs
If we don't have a .ChorusNotes file we don't have to create one in
LfMergeBridge because that is done in Chorus. Just creating a text file
caused a crash when Chorus tried to read the file as XML.
The .ChorusNotes file won't exist if the user sends an empty project
(without any entries) in FLEx and we S/R to LF.
This change also adds a unit test for the case when the .ChorusNotes file
is missing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/240)
>  Fix crash if we don't have a .ChorusNotes file (LF-199)

- src/InstallerOverrides/CustomComponents.wxi
- src/InstallerOverrides/CustomFeatures.wxi
So that FLEx 8 can use the latest version of FLEx Bridge, which was designed to be found by FLEx 9.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/239)
> add FLEXBRIDGEDIR Env Var to Win installer

- src/LibFLExBridge-ChorusPlugin/Contexts/BaseDomainServices.cs
- src/LibFLExBridge-ChorusPlugin/Contexts/General/GeneralDomainBoundedContext.cs
- src/LibFLExBridge-ChorusPlugin/Handling/Common/ProjectLexiconSettingsStrategy.cs
- src/LibFLExBridge-ChorusPlugin/Handling/FieldWorksCommonFileHandler.cs
- src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeConstants.cs
- src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexFolderSystem.cs
- src/LibFLExBridge-ChorusPlugin/LibFLExBridge-ChorusPlugin.csproj
- src/LibFLExBridge-ChorusPluginTests/FieldWorksTestServices.cs
- src/LibFLExBridge-ChorusPluginTests/Handling/Common/ProjectLexiconSettingsTypeHandlerTests.cs
- src/LibFLExBridge-ChorusPluginTests/LibFLExBridge-ChorusPluginTests.csproj
- src/TriboroughBridge-ChorusPlugin/TriboroughBridgeUtilities.cs
* Handle .plsx and .ulsx files
* Copy settings files to and from a Cached folder during S/R
* Configure the repo to include the Cached folder instead of the
plain folders
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/247)
> Add file handler for lexicon settings

- src/LibFLExBridge-ChorusPlugin/Contexts/BaseDomainServices.cs
Some projects are missing the `ConfigurationSettings` folder, which causes the `DirectoryHelper.Copy` call to fail because the source folder doesn't exist. (`DirectoryHelper.Copy` will create a *destination* folder if it doesn't exist, but it throws an exception if the *source* folder doesn't exist.) If the project doesn't have a settings folder, there's no need to copy it into the cache. https://github.com/sillsdev/flexbridge/commit/f5f45ae1d5aa290b5b99148f8e7a4a97ce7667a2 (which was an extension to https://github.com/sillsdev/flexbridge/pull/247) already makes this change in the part of the code that copies settings folders out of the cache into the project, but didn't do anything for the project->cache direction. It turns out that the project->cache direction is needed too: while doing …
> Only copy settings directories that actually exist

- Makefile
- debian/control
Putting /usr/bin/python into the focal package may introduce conflicts
or other problems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/259)
> Or depend on python2, for Ubuntu 20.04

- src/FLEx-ChorusPlugin/Infrastructure/ActionHandlers/ObtainProjectStrategyFlex.cs
- src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeConstants.cs
- src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexBridgeSynchronizerAdjunct.cs
- src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexUpdateBranchHelperStrategy.cs
- src/LibTriboroughBridge-ChorusPlugin/Infrastructure/IUpdateBranchHelperStrategy.cs
- src/LibTriboroughBridge-ChorusPlugin/Infrastructure/UpdateBranchHelper.cs
- src/LiftBridge-ChorusPlugin/Infrastructure/UpdateBranchHelperLift.cs
- src/TriboroughBridge-ChorusPlugin/CommandLineProcessor.cs
The branch name that FlexBridge uses will now be made up of ModelVersion.FlexBridgeDataVersion
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/263)
> Add to FlexBridge a version number (LT-20019)

- GitVersion.yml
- build/WixPatchableInstaller.targets
- debian/changelog
- src/Installer/Beta.htm
- src/Installer/ReleaseNotes.md
* Include Chorus bugfix for LT-20019
* Change 'unstable' tag to 'beta' for develop
branch builds
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/264)
> Updated version to 3.1.3

- .vscode/launch.json
- .vscode/tasks.json
* Set PATH, to use a specific mono when running FB.
* Added documentation for launching in various ways. An improvement
would be to have different configurations launch FB in different
modes, but the project would still need manually specified in the
arguments.
* Add build tasks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/267)
> Enhance VSCode building and launching

- Makefile
* Preventing FLExBridge.exe.config from specifying gtk-sharp 3.0.0.0.
* Fixes LT-20123.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/268)
> Override AutoGenerateBindingRedirects to false on Linux

- FLExBridge.sln.DotSettings
- UpdateDependencies.bat
- download_dependencies_linux.sh
- download_dependencies_windows.sh
- src/FLEx-ChorusPlugin/FLEx-ChorusPlugin.csproj
- src/FLEx-ChorusPlugin/packages.config
- src/FLExBridge/FLExBridge.csproj
- src/FLExBridge/packages.config
- src/FwdataNester/FwdataTestApp.csproj
- src/FwdataNester/packages.config
- src/LibTriboroughBridge-ChorusPlugin/Infrastructure/UpdateBranchHelper.cs
- src/LiftBridge-ChorusPlugin/LiftBridge-ChorusPlugin.csproj
- src/LiftBridge-ChorusPlugin/packages.config
- src/RepositoryUtility/RepositoryUtility.csproj
- src/RepositoryUtility/packages.config
- src/TriboroughBridge-ChorusPlugin/TriboroughBridge-ChorusPlugin.csproj
- src/TriboroughBridge-ChorusPlugin/TriboroughBridgeUtilities.cs
- src/TriboroughBridge-ChorusPlugin/packages.config
Download L10NSharp.dll from TeamCity Palaso build.
Because everyone (at least Chorus and FLEx) uses L10NSharp.dll
from Palaso builds, there will be no version conflicts.
(This is what FLEx Bridge builds were already doing on TeamCity.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/271)
> Fix L10nSharp load problem

- Makefile
- ReadMe.md
- UpdateDependencies.bat
- build/FLExBridge.proj
- build/build.bat
- l10n/l10n.proj
* Download and copy Palaso and Chorus L10ns in build.bat
* Depend on RestoreBuildTasks prior to depending on downloaded
build task GetVersion (so developers who don't follow
instructions can at least build successfully on their second try
* Remove Mercurial instructions that have been superseded by an
automatic step
* Update documentation for building against a locally-built Chorus
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/275)
> Help Developers Get Started

- debian/control
- debian/rules
* Since package is not available for focal presently.
* tar is extracted into /usr/local/share/dotnet, with symlink
from /usr/local/bin/dotnet to /usr/local/share/dotnet/dotnet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/278)
> Handle dotnet-sdk dependency manually

- Makefile
- debian/rules
* Since focal package is not available yet.
* Can't write to /usr or seemingly anywhere but /tmp, /var/tmp, and
/build during sbuild. Install to
/var/tmp/buildhome/.local/share/dotnet, and access via
/var/tmp/buildhome/.local/bin being in the path.
* The dotnet sdk tar didn't seem to ship with a
dotnet-cli-tools-bin-path.sh file. Just manually appending
HOME/.dotnet/tools to path to find overcrowdin, in Makefile.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/280)
> Install dotnet sdk from tar

- src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexUpdateBranchHelperStrategy.cs
- src/LibFLExBridge-ChorusPluginTests/Infrastructure/FlexUpdateBranchHelperStrategyTests.cs
- src/LibFLExBridge-ChorusPluginTests/LibFLExBridge-ChorusPluginTests.csproj
* Parse the branch name using invariant culture to
avoid crashes when users have their OS displaying
in Scandinavian languages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/282)
> Fix crash using FB in Swedish locale

- src/LfMergeBridge/LanguageForgeMakeCloneActionHandler.cs
- src/LfMergeBridge/LanguageForgeSendReceiveActionHandler.cs
- src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexUpdateBranchHelperStrategy.cs
- src/LibTriboroughBridge-ChorusPlugin/Infrastructure/IUpdateBranchHelperStrategy.cs
- src/LiftBridge-ChorusPlugin/Infrastructure/UpdateBranchHelperLift.cs
Now that model versions are doubles, we need to change some of the int.Parse calls in LfMergeBridge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/285)
> Fix model version parsing after #263

- src/LfMergeBridge/LanguageForgeMakeCloneActionHandler.cs
- src/LibFLExBridge-ChorusPlugin/Infrastructure/FlexUpdateBranchHelperStrategy.cs
Repos cloned with LfMerge versions from before the FLExBridge change may have branch name 7000072 in them, so we can't just assume that that branch name won't ever be present. So the conditional in FinishClone was wrong; removing it makes LfMerge unit tests pass again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/291)
> Better handle pre-change LfMerge repos

- src/LibFLExBridge-ChorusPlugin/Contexts/BaseDomainServices.cs
- src/LibFLExBridge-ChorusPluginTests/Infrastructure/FLExProjectSplitterTests.cs
* Fix LT-20464 - Remove project settings files
from the cache if they are no longer in the
source folders
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/295)
> Clear removed project settings from the cache

- Makefile
- build/nuget-linux/packages.config
- environ-xulrunner
- src/FLExBridge/FLExBridge.csproj
- src/RepositoryUtility/RepositoryUtility.csproj
To match GeckoFx version used by FieldWorks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/308)
> Upgrade to GeckoFx 60 and drop 32-bit support

- flexbridge
We're not sourcing environ, but we still need
this one variable to be set when we're running.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/312)
> set HGRCPATH

- Makefile
- appveyor.yml
- build/FLExBridge.proj
- src/FLEx-ChorusPluginTests/FLEx-ChorusPluginTests.csproj
- src/LfMergeBridgeTests/LfMergeBridgeTests.csproj
- src/LibFLExBridge-ChorusPluginTests/LibFLExBridge-ChorusPluginTests.csproj
- src/LiftBridge-ChorusPluginTests/LiftBridge-ChorusPluginTests.csproj
- src/TriboroughBridge-ChorusPluginTests/TriboroughBridge-ChorusPluginTests.csproj
Allow to build package without running gitversion during binary package build. Instead run gitversion before creating the source
package which creates a json file. Then during binary package build we use the json file to populate the necessary properties.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/flexbridge/324)
> Fix packaging
